//Адреса маршрутов

export const NULL_ROUTE = '/404page'
export const MAIN_ROUTE = '/main'
export const MOSCOW_ROUTE = '/moscow'
export const NN_ROUTE = '/grecords_website'//nnovgorod'
export const SAMARA_ROUTE = '/samara'
export const MANIFESTO_ROUTE = '/manifesto'
export const TEAM_ROUTE = '/team'
export const PROFESSIONALS_ROUTE = '/professionals'
export const ENTHUSIATS_ROUTE = '/enthusiasts'
export const BUSINES_ROUTE = '/busines'
export const PRIVACY_POLICY_ROUTE = '/privacy_policy'
export const CONTACTS_ROUTE = '/contacts'
export const CITY_CONTACTS_ROUTE='/contacts/:city'
export const ACADEMY_ROUTE = '/academy'
export const SHOP_ROUTE = '/shop'
export const EVENTS_ROUTE = '/events'
export const CONTACTS_NN_ROUTE='/contacts/nnovgorod'

